### ISSUE TITLE
Implement progress indicator in speed read

### ISSUE THREAD

**Issue by travelinreid** [michigan-com/nova#20]

**Comment by migreva** [comment]
![803707036_5491910671708809831](https://cloud.githubusercontent.com/assets/2940659/15364503/d13681aa-1cea-11e6-9c38-2c4121f417a4.jpg)

![iphone 6_2](https://cloud.githubusercontent.com/assets/2940659/15364473/b8871f98-1cea-11e6-90f5-9c4f14d330ed.png)
![iphone 6_3](https://cloud.githubusercontent.com/assets/2940659/15364475/b9b0a542-1cea-11e6-837a-f51f31695b00.png)

**Comment by migreva** [comment]
![iphone 6_red](https://cloud.githubusercontent.com/assets/2940659/15364658/40ce0e66-1ceb-11e6-88ce-63ed3ca6c511.png)

**Comment by migreva** [comment]
https://github.com/michigan-com/nova/commit/8b9affa126d81d2cdd369cd709c5df095fc37340

**Comment by migreva** [comment]
https://github.com/michigan-com/nova/commit/c56b4fabc899e23c37ff68f47e133534ce0c8976
