### ISSUE TITLE
Develop service to listen for breaking news emails & generate summaries & SMS messages

### ISSUE THREAD

**Issue by travelinreid** [michigan-com/nova#25]

**Comment by travelinreid** [comment]
To start, I was thinking more just listen for the newsroom emails ...

**Comment by migreva** [comment]
Turned this into a `gannett-newsfetch` command that runs in a loop waiting to find breaking news articles

https://github.com/michigan-com/gannett-newsfetch/blob/master/commands/breaking.go#L21
