### ISSUE TITLE
Investigate Twilio MMS

### ISSUE THREAD

**Issue by travelinreid** [michigan-com/nova#37]

**Comment by migreva** [comment]
https://www.twilio.com/docs/api/rest/sending-messages#post-parameters-conditional

Looks like we can specify an image using "Media URL", this will require us to pre-fetch the article content which shouldn't be hard to do. That would actually help us with the consistency of data in the breaking news alerts: we dont send it out as a breaking news item if we can't scrape it from the API

**Comment by travelinreid** [comment]
We need to build a good library of gifs that we can use in sending users
system messages and prompts.

**Comment by migreva** [comment]
That's a great idea, ties into our desire to keep this app loose and fun
